### ISSUE TITLE
ERROR: Out of stack space

### ISSUE THREAD

**Issue by bissolli** [mathieustan/vue-datepicker#52]
Since we updated from `0.2.1` to the latest version we've been experiencing on Edge and IE so far.

Any idea on what could cause it? As I work on MacOS I honestly couldn't reproduce, but I've got quite a few warnings on Sentry regarding that, so I might be affecting more people.

Stack-trace:
```
Error: Out of stack space
  at It (./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:66747)
  at It (./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:66747)
  at It (./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:66747)
  at It (./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:66747)
  at It (./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:66747)
...
(45 additional frame(s) were not displayed)
```

Thanks

**Comment by mathieustan** [comment]
I’ll check that. Thx.

**Comment by bissolli** [comment]
Thanks @mathieustan .

I have a new insight for you on that:
```
InternalError: too much recursion
  at every (./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:66895)
  at Rt/< (./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:66867)
  at It (./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:66754)
  at It (./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:66923)
  at It (./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:66923)
...
(45 additional frame(s) were not displayed)
```

**Comment by mathieustan** [comment]
Hello @bissolli. 

Is the doc working for you on IE11|Edge ? I don't have any error. 
Only grid are broken, i'm looking toi fix that.

**Comment by mathieustan** [comment]
Close for now. Let me know if there is still a problem
