### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by maniyadv** [mathieustan/vue-datepicker#83]
This seems related to this closed issue - https://github.com/mathieustan/vue-datepicker/issues/54
Scenario - When user's browser language set to any other language than English, date picker is unable to initialise.
Workaround - Set locale explicitly to english using - `:locale="{lang: 'en'}"` prop.

```
RangeError: Maximum call stack size exceeded
  at ? (./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:73274)
  at Xt(./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:73274)
  at Xt(./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:73444)
```

**Comment by colesnic89** [comment]
> This seems related to this closed issue - #54
> 
> **Scenario** - When user's browser language set to any other language than English, date picker is unable to initialise.
> **Workaround** - Set locale explicitly to english using - `:locale="{lang: 'en'}"` prop.
> 
> ```
> RangeError: Maximum call stack size exceeded
>   at ? (./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:73274)
>   at Xt(./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:73274)
>   at Xt(./node_modules/@mathieustan/vue-datepicker/dist/vue-datepicker.esm.js:5:73444)
> ```

For Russian language all is ok. But for Romanian I have the same error

**Comment by VirajSingh19** [comment]
could be related to [ unsupported browser language](https://github.com/mathieustan/vue-datepicker/issues/84)

**Comment by ItsJoeTurner** [comment]
Has anyone found a real solution for this? The numbers do not show for some of my users outside the UK even with lang: 'en' selected.

**Comment by maniyadv** [comment]
> Has anyone found a real solution for this? The numbers do not show for some of my users outside the UK even with lang: 'en' selected.

If you are not already doing it make sure you use v-bind on the prop by using -  `:locale="{lang: 'en'}"` or `v-bind:locale="{lang: 'en'}"`
So that it receives object instead of string. That way it worked fine for me.
